// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"rigor/client/checks"
	"rigor/client/comparison_reports"
	"rigor/client/http_checks"
	"rigor/client/real_browser_checks"
	"rigor/client/system_events"
)

// Default rigor HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "monitoring-api.rigor.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new rigor HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Rigor {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new rigor HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Rigor {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new rigor client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Rigor {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Rigor)
	cli.Transport = transport
	cli.Checks = checks.New(transport, formats)
	cli.ComparisonReports = comparison_reports.New(transport, formats)
	cli.HTTPChecks = http_checks.New(transport, formats)
	cli.RealBrowserChecks = real_browser_checks.New(transport, formats)
	cli.SystemEvents = system_events.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Rigor is a client for rigor
type Rigor struct {
	Checks checks.ClientService

	ComparisonReports comparison_reports.ClientService

	HTTPChecks http_checks.ClientService

	RealBrowserChecks real_browser_checks.ClientService

	SystemEvents system_events.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Rigor) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Checks.SetTransport(transport)
	c.ComparisonReports.SetTransport(transport)
	c.HTTPChecks.SetTransport(transport)
	c.RealBrowserChecks.SetTransport(transport)
	c.SystemEvents.SetTransport(transport)
}
