// Code generated by go-swagger; DO NOT EDIT.

package real_browser_checks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/greatestusername/synthetics-go-client/models"
)

// GetRealBrowserCheckRunsReader is a Reader for the GetRealBrowserCheckRuns structure.
type GetRealBrowserCheckRunsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRealBrowserCheckRunsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRealBrowserCheckRunsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetRealBrowserCheckRunsOK creates a GetRealBrowserCheckRunsOK with default headers values
func NewGetRealBrowserCheckRunsOK() *GetRealBrowserCheckRunsOK {
	return &GetRealBrowserCheckRunsOK{}
}

/* GetRealBrowserCheckRunsOK describes a response with status code 200, with default header values.

Real Browser check runs response
*/
type GetRealBrowserCheckRunsOK struct {
	Payload *models.RealBrowserCheckRunCollection
}

func (o *GetRealBrowserCheckRunsOK) Error() string {
	return fmt.Sprintf("[GET /v2/checks/real_browsers/{check_id}/runs][%d] getRealBrowserCheckRunsOK  %+v", 200, o.Payload)
}
func (o *GetRealBrowserCheckRunsOK) GetPayload() *models.RealBrowserCheckRunCollection {
	return o.Payload
}

func (o *GetRealBrowserCheckRunsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RealBrowserCheckRunCollection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
