// Code generated by go-swagger; DO NOT EDIT.

package checks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCheckMetricsParams creates a new GetCheckMetricsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCheckMetricsParams() *GetCheckMetricsParams {
	return &GetCheckMetricsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCheckMetricsParamsWithTimeout creates a new GetCheckMetricsParams object
// with the ability to set a timeout on a request.
func NewGetCheckMetricsParamsWithTimeout(timeout time.Duration) *GetCheckMetricsParams {
	return &GetCheckMetricsParams{
		timeout: timeout,
	}
}

// NewGetCheckMetricsParamsWithContext creates a new GetCheckMetricsParams object
// with the ability to set a context for a request.
func NewGetCheckMetricsParamsWithContext(ctx context.Context) *GetCheckMetricsParams {
	return &GetCheckMetricsParams{
		Context: ctx,
	}
}

// NewGetCheckMetricsParamsWithHTTPClient creates a new GetCheckMetricsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCheckMetricsParamsWithHTTPClient(client *http.Client) *GetCheckMetricsParams {
	return &GetCheckMetricsParams{
		HTTPClient: client,
	}
}

/* GetCheckMetricsParams contains all the parameters to send to the API endpoint
   for the get check metrics operation.

   Typically these are written to a http.Request.
*/
type GetCheckMetricsParams struct {

	/* ID.

	   ID of check to fetch

	   Format: int32
	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get check metrics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCheckMetricsParams) WithDefaults() *GetCheckMetricsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get check metrics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCheckMetricsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get check metrics params
func (o *GetCheckMetricsParams) WithTimeout(timeout time.Duration) *GetCheckMetricsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get check metrics params
func (o *GetCheckMetricsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get check metrics params
func (o *GetCheckMetricsParams) WithContext(ctx context.Context) *GetCheckMetricsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get check metrics params
func (o *GetCheckMetricsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get check metrics params
func (o *GetCheckMetricsParams) WithHTTPClient(client *http.Client) *GetCheckMetricsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get check metrics params
func (o *GetCheckMetricsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get check metrics params
func (o *GetCheckMetricsParams) WithID(id int32) *GetCheckMetricsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get check metrics params
func (o *GetCheckMetricsParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCheckMetricsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
