// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CheckEscalationInput An additional notification to send if an alert is unacknowledged
//
// swagger:model check_escalation_input
type CheckEscalationInput struct {
	CheckEscalation
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *CheckEscalationInput) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 CheckEscalation
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.CheckEscalation = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m CheckEscalationInput) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.CheckEscalation)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this check escalation input
func (m *CheckEscalationInput) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with CheckEscalation
	if err := m.CheckEscalation.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this check escalation input based on the context it is used
func (m *CheckEscalationInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with CheckEscalation
	if err := m.CheckEscalation.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *CheckEscalationInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CheckEscalationInput) UnmarshalBinary(b []byte) error {
	var res CheckEscalationInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
