// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// HTTPCheckInput The parameters for an HTTP check
//
// swagger:model http_check_input
type HTTPCheckInput struct {
	HTTPCheckInputAllOf0

	// connection
	Connection *HTTPCheckInputAO1Connection `json:"connection,omitempty"`

	// http method
	// Enum: [GET HEAD POST POST/XML PUT DELETE]
	HTTPMethod *string `json:"http_method,omitempty"`

	// Request body to send (e.g. post data).
	HTTPRequestBody string `json:"http_request_body,omitempty"`

	// success criteria
	SuccessCriteria []*HTTPCheckInputSuccessCriteriaItems0 `json:"success_criteria"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *HTTPCheckInput) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 HTTPCheckInputAllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.HTTPCheckInputAllOf0 = aO0

	// AO1
	var dataAO1 struct {
		Connection *HTTPCheckInputAO1Connection `json:"connection,omitempty"`

		HTTPMethod *string `json:"http_method,omitempty"`

		HTTPRequestBody string `json:"http_request_body,omitempty"`

		SuccessCriteria []*HTTPCheckInputSuccessCriteriaItems0 `json:"success_criteria"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Connection = dataAO1.Connection

	m.HTTPMethod = dataAO1.HTTPMethod

	m.HTTPRequestBody = dataAO1.HTTPRequestBody

	m.SuccessCriteria = dataAO1.SuccessCriteria

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m HTTPCheckInput) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.HTTPCheckInputAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Connection *HTTPCheckInputAO1Connection `json:"connection,omitempty"`

		HTTPMethod *string `json:"http_method,omitempty"`

		HTTPRequestBody string `json:"http_request_body,omitempty"`

		SuccessCriteria []*HTTPCheckInputSuccessCriteriaItems0 `json:"success_criteria"`
	}

	dataAO1.Connection = m.Connection

	dataAO1.HTTPMethod = m.HTTPMethod

	dataAO1.HTTPRequestBody = m.HTTPRequestBody

	dataAO1.SuccessCriteria = m.SuccessCriteria

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this http check input
func (m *HTTPCheckInput) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with HTTPCheckInputAllOf0
	if err := m.HTTPCheckInputAllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConnection(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHTTPMethod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSuccessCriteria(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HTTPCheckInput) validateConnection(formats strfmt.Registry) error {

	if swag.IsZero(m.Connection) { // not required
		return nil
	}

	if m.Connection != nil {
		if err := m.Connection.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("connection")
			}
			return err
		}
	}

	return nil
}

var httpCheckInputTypeHTTPMethodPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["GET","HEAD","POST","POST/XML","PUT","DELETE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		httpCheckInputTypeHTTPMethodPropEnum = append(httpCheckInputTypeHTTPMethodPropEnum, v)
	}
}

// property enum
func (m *HTTPCheckInput) validateHTTPMethodEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, httpCheckInputTypeHTTPMethodPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *HTTPCheckInput) validateHTTPMethod(formats strfmt.Registry) error {

	if swag.IsZero(m.HTTPMethod) { // not required
		return nil
	}

	// value enum
	if err := m.validateHTTPMethodEnum("http_method", "body", *m.HTTPMethod); err != nil {
		return err
	}

	return nil
}

func (m *HTTPCheckInput) validateSuccessCriteria(formats strfmt.Registry) error {

	if swag.IsZero(m.SuccessCriteria) { // not required
		return nil
	}

	for i := 0; i < len(m.SuccessCriteria); i++ {
		if swag.IsZero(m.SuccessCriteria[i]) { // not required
			continue
		}

		if m.SuccessCriteria[i] != nil {
			if err := m.SuccessCriteria[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("success_criteria" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this http check input based on the context it is used
func (m *HTTPCheckInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with HTTPCheckInputAllOf0
	if err := m.HTTPCheckInputAllOf0.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateConnection(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSuccessCriteria(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HTTPCheckInput) contextValidateConnection(ctx context.Context, formats strfmt.Registry) error {

	if m.Connection != nil {
		if err := m.Connection.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("connection")
			}
			return err
		}
	}

	return nil
}

func (m *HTTPCheckInput) contextValidateSuccessCriteria(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SuccessCriteria); i++ {

		if m.SuccessCriteria[i] != nil {
			if err := m.SuccessCriteria[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("success_criteria" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HTTPCheckInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPCheckInput) UnmarshalBinary(b []byte) error {
	var res HTTPCheckInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// HTTPCheckInputAO1Connection HTTP check input a o1 connection
//
// swagger:model HTTPCheckInputAO1Connection
type HTTPCheckInputAO1Connection struct {

	// The upper limit imposed on all incoming network traffic in Kbps
	DownloadBandwidth *int64 `json:"download_bandwidth,omitempty"`

	// The latency that is added to each request in milliseconds
	Latency *int64 `json:"latency,omitempty"`

	// The percentage of all incoming or outgoing packets that are intentionally dropped
	PacketLoss float64 `json:"packet_loss,omitempty"`

	// The upper limit imposed on all outgoing network traffic in Kbps
	UploadBandwidth *int64 `json:"upload_bandwidth,omitempty"`
}

// Validate validates this HTTP check input a o1 connection
func (m *HTTPCheckInputAO1Connection) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this HTTP check input a o1 connection based on context it is used
func (m *HTTPCheckInputAO1Connection) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPCheckInputAO1Connection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPCheckInputAO1Connection) UnmarshalBinary(b []byte) error {
	var res HTTPCheckInputAO1Connection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// HTTPCheckInputAllOf0 An uptime check
//
// swagger:model HTTPCheckInputAllOf0
type HTTPCheckInputAllOf0 struct {
	HTTPCheckInputAllOf0AllOf0

	// url
	URL string `json:"url,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *HTTPCheckInputAllOf0) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 HTTPCheckInputAllOf0AllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.HTTPCheckInputAllOf0AllOf0 = aO0

	// AO1
	var dataAO1 struct {
		URL string `json:"url,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.URL = dataAO1.URL

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m HTTPCheckInputAllOf0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.HTTPCheckInputAllOf0AllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		URL string `json:"url,omitempty"`
	}

	dataAO1.URL = m.URL

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this HTTP check input all of0
func (m *HTTPCheckInputAllOf0) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with HTTPCheckInputAllOf0AllOf0
	if err := m.HTTPCheckInputAllOf0AllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this HTTP check input all of0 based on the context it is used
func (m *HTTPCheckInputAllOf0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with HTTPCheckInputAllOf0AllOf0
	if err := m.HTTPCheckInputAllOf0AllOf0.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPCheckInputAllOf0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPCheckInputAllOf0) UnmarshalBinary(b []byte) error {
	var res HTTPCheckInputAllOf0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// HTTPCheckInputAllOf0AllOf0 A monitoring check
//
// swagger:model HTTPCheckInputAllOf0AllOf0
type HTTPCheckInputAllOf0AllOf0 struct {

	// Run the check at this interval (in minutes)
	// Example: 5
	// Required: true
	Frequency *int64 `json:"frequency"`

	// The unique name for the check
	// Required: true
	Name *string `json:"name"`

	// An array of tag names to apply to the check
	Tags []string `json:"tags"`

	// When enabled, the check will retry up to two times from the same location after a failed run. Ensure your account plan supports this feature before enabling.
	AutoRetry *bool `json:"auto_retry,omitempty"`

	// True if the check is not paused
	Enabled *bool `json:"enabled,omitempty"`

	// http request headers
	HTTPRequestHeaders interface{} `json:"http_request_headers,omitempty"`

	// The integrations to send metrics to
	Integrations []int32 `json:"integrations"`

	// The locations to run the check from
	Locations []int32 `json:"locations"`

	// Configure how and when alerts are sent
	Notifications struct {

		// escalations
		Escalations []*HTTPCheckInputAllOf0AllOf0EscalationsItems0 `json:"escalations"`

		// Muted checks do not send any alert notifications
		Muted *bool `json:"muted,omitempty"`

		// Alert once the number of failed runs reaches this threshold.
		//                                    Recommended threshold is 2.
		// Maximum: 10
		// Minimum: 1
		NotifyAfterFailureCount int32 `json:"notify_after_failure_count,omitempty"`

		// Alert if the check is failing from only one location
		NotifyOnLocationFailure *bool `json:"notify_on_location_failure,omitempty"`

		// notify who
		// Unique: true
		NotifyWho []*HTTPCheckInputAllOf0AllOf0NotifyWhoItems0 `json:"notify_who"`

		// Notify via phone call (requires that the recipient has a valid phone number and accepts phone call alerts)
		Call *bool `json:"call,omitempty"`

		// Notify via email
		Email *bool `json:"email,omitempty"`

		// Notify via SMS (requires that the recipient has a valid phone number and accepts SMS alerts)
		Sms *bool `json:"sms,omitempty"`
	} `json:"notifications,omitempty"`

	// Mark a run as a failure if the total response time
	//                                    is above this threshold (in milliseconds)
	// Maximum: 60000
	// Minimum: 0
	ResponseTimeMonitorMilliseconds *int32 `json:"response_time_monitor_milliseconds,omitempty"`

	// When enabled, the check cycles through locations round-robin style with each run.Ensure your account plan supports concurrent checks before disabling.
	RoundRobin *bool `json:"round_robin,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *HTTPCheckInputAllOf0AllOf0) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		Frequency *int64 `json:"frequency"`

		Name *string `json:"name"`

		Tags []string `json:"tags"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.Frequency = dataAO0.Frequency

	m.Name = dataAO0.Name

	m.Tags = dataAO0.Tags

	// AO1
	var dataAO1 struct {
		AutoRetry *bool `json:"auto_retry,omitempty"`

		Enabled *bool `json:"enabled,omitempty"`

		HTTPRequestHeaders interface{} `json:"http_request_headers,omitempty"`

		Integrations []int32 `json:"integrations"`

		Locations []int32 `json:"locations"`

		Notifications struct {

			// escalations
			Escalations []*HTTPCheckInputAllOf0AllOf0EscalationsItems0 `json:"escalations"`

			// Muted checks do not send any alert notifications
			Muted *bool `json:"muted,omitempty"`

			// Alert once the number of failed runs reaches this threshold.
			//                                    Recommended threshold is 2.
			// Maximum: 10
			// Minimum: 1
			NotifyAfterFailureCount int32 `json:"notify_after_failure_count,omitempty"`

			// Alert if the check is failing from only one location
			NotifyOnLocationFailure *bool `json:"notify_on_location_failure,omitempty"`

			// notify who
			// Unique: true
			NotifyWho []*HTTPCheckInputAllOf0AllOf0NotifyWhoItems0 `json:"notify_who"`

			// Notify via phone call (requires that the recipient has a valid phone number and accepts phone call alerts)
			Call *bool `json:"call,omitempty"`

			// Notify via email
			Email *bool `json:"email,omitempty"`

			// Notify via SMS (requires that the recipient has a valid phone number and accepts SMS alerts)
			Sms *bool `json:"sms,omitempty"`
		} `json:"notifications,omitempty"`

		ResponseTimeMonitorMilliseconds *int32 `json:"response_time_monitor_milliseconds,omitempty"`

		RoundRobin *bool `json:"round_robin,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.AutoRetry = dataAO1.AutoRetry

	m.Enabled = dataAO1.Enabled

	m.HTTPRequestHeaders = dataAO1.HTTPRequestHeaders

	m.Integrations = dataAO1.Integrations

	m.Locations = dataAO1.Locations

	m.Notifications = dataAO1.Notifications

	m.ResponseTimeMonitorMilliseconds = dataAO1.ResponseTimeMonitorMilliseconds

	m.RoundRobin = dataAO1.RoundRobin

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m HTTPCheckInputAllOf0AllOf0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		Frequency *int64 `json:"frequency"`

		Name *string `json:"name"`

		Tags []string `json:"tags"`
	}

	dataAO0.Frequency = m.Frequency

	dataAO0.Name = m.Name

	dataAO0.Tags = m.Tags

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	var dataAO1 struct {
		AutoRetry *bool `json:"auto_retry,omitempty"`

		Enabled *bool `json:"enabled,omitempty"`

		HTTPRequestHeaders interface{} `json:"http_request_headers,omitempty"`

		Integrations []int32 `json:"integrations"`

		Locations []int32 `json:"locations"`

		Notifications struct {

			// escalations
			Escalations []*HTTPCheckInputAllOf0AllOf0EscalationsItems0 `json:"escalations"`

			// Muted checks do not send any alert notifications
			Muted *bool `json:"muted,omitempty"`

			// Alert once the number of failed runs reaches this threshold.
			//                                    Recommended threshold is 2.
			// Maximum: 10
			// Minimum: 1
			NotifyAfterFailureCount int32 `json:"notify_after_failure_count,omitempty"`

			// Alert if the check is failing from only one location
			NotifyOnLocationFailure *bool `json:"notify_on_location_failure,omitempty"`

			// notify who
			// Unique: true
			NotifyWho []*HTTPCheckInputAllOf0AllOf0NotifyWhoItems0 `json:"notify_who"`

			// Notify via phone call (requires that the recipient has a valid phone number and accepts phone call alerts)
			Call *bool `json:"call,omitempty"`

			// Notify via email
			Email *bool `json:"email,omitempty"`

			// Notify via SMS (requires that the recipient has a valid phone number and accepts SMS alerts)
			Sms *bool `json:"sms,omitempty"`
		} `json:"notifications,omitempty"`

		ResponseTimeMonitorMilliseconds *int32 `json:"response_time_monitor_milliseconds,omitempty"`

		RoundRobin *bool `json:"round_robin,omitempty"`
	}

	dataAO1.AutoRetry = m.AutoRetry

	dataAO1.Enabled = m.Enabled

	dataAO1.HTTPRequestHeaders = m.HTTPRequestHeaders

	dataAO1.Integrations = m.Integrations

	dataAO1.Locations = m.Locations

	dataAO1.Notifications = m.Notifications

	dataAO1.ResponseTimeMonitorMilliseconds = m.ResponseTimeMonitorMilliseconds

	dataAO1.RoundRobin = m.RoundRobin

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this HTTP check input all of0 all of0
func (m *HTTPCheckInputAllOf0AllOf0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFrequency(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNotifications(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResponseTimeMonitorMilliseconds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HTTPCheckInputAllOf0AllOf0) validateFrequency(formats strfmt.Registry) error {

	if err := validate.Required("frequency", "body", m.Frequency); err != nil {
		return err
	}

	return nil
}

func (m *HTTPCheckInputAllOf0AllOf0) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *HTTPCheckInputAllOf0AllOf0) validateNotifications(formats strfmt.Registry) error {

	if swag.IsZero(m.Notifications) { // not required
		return nil
	}

	for i := 0; i < len(m.Notifications.Escalations); i++ {
		if swag.IsZero(m.Notifications.Escalations[i]) { // not required
			continue
		}

		if m.Notifications.Escalations[i] != nil {
			if err := m.Notifications.Escalations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("notifications" + "." + "escalations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if err := validate.MinimumInt("notifications"+"."+"notify_after_failure_count", "body", int64(m.Notifications.NotifyAfterFailureCount), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("notifications"+"."+"notify_after_failure_count", "body", int64(m.Notifications.NotifyAfterFailureCount), 10, false); err != nil {
		return err
	}

	if err := validate.UniqueItems("notifications"+"."+"notify_who", "body", m.Notifications.NotifyWho); err != nil {
		return err
	}

	for i := 0; i < len(m.Notifications.NotifyWho); i++ {
		if swag.IsZero(m.Notifications.NotifyWho[i]) { // not required
			continue
		}

		if m.Notifications.NotifyWho[i] != nil {
			if err := m.Notifications.NotifyWho[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("notifications" + "." + "notify_who" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *HTTPCheckInputAllOf0AllOf0) validateResponseTimeMonitorMilliseconds(formats strfmt.Registry) error {

	if swag.IsZero(m.ResponseTimeMonitorMilliseconds) { // not required
		return nil
	}

	if err := validate.MinimumInt("response_time_monitor_milliseconds", "body", int64(*m.ResponseTimeMonitorMilliseconds), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("response_time_monitor_milliseconds", "body", int64(*m.ResponseTimeMonitorMilliseconds), 60000, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this HTTP check input all of0 all of0 based on the context it is used
func (m *HTTPCheckInputAllOf0AllOf0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateNotifications(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HTTPCheckInputAllOf0AllOf0) contextValidateNotifications(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Notifications.Escalations); i++ {

		if m.Notifications.Escalations[i] != nil {
			if err := m.Notifications.Escalations[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("notifications" + "." + "escalations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	for i := 0; i < len(m.Notifications.NotifyWho); i++ {

		if m.Notifications.NotifyWho[i] != nil {
			if err := m.Notifications.NotifyWho[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("notifications" + "." + "notify_who" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HTTPCheckInputAllOf0AllOf0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPCheckInputAllOf0AllOf0) UnmarshalBinary(b []byte) error {
	var res HTTPCheckInputAllOf0AllOf0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// HTTPCheckInputAllOf0AllOf0EscalationsItems0 An additional notification to send if an alert is unacknowledged
//
// swagger:model HTTPCheckInputAllOf0AllOf0EscalationsItems0
type HTTPCheckInputAllOf0AllOf0EscalationsItems0 struct {

	// Minutes to wait before escalating
	AfterMinutes int32 `json:"after_minutes,omitempty"`

	// Notify via phone call (requires that the recipient has a valid phone number)
	Call *bool `json:"call,omitempty"`

	// Notify via email
	Email *bool `json:"email,omitempty"`

	// Repeat the escalation if the alert is still unacknowledged
	IsRepeat *bool `json:"is_repeat,omitempty"`

	// notification window
	NotificationWindow *HTTPCheckInputAllOf0AllOf0EscalationsItems0AO0NotificationWindow `json:"notification_window,omitempty"`

	// notify who
	NotifyWho []*HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0 `json:"notify_who"`

	// Notify via SMS (requires that the recipient has a valid phone number)
	Sms *bool `json:"sms,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		AfterMinutes int32 `json:"after_minutes,omitempty"`

		Call *bool `json:"call,omitempty"`

		Email *bool `json:"email,omitempty"`

		IsRepeat *bool `json:"is_repeat,omitempty"`

		NotificationWindow *HTTPCheckInputAllOf0AllOf0EscalationsItems0AO0NotificationWindow `json:"notification_window,omitempty"`

		NotifyWho []*HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0 `json:"notify_who"`

		Sms *bool `json:"sms,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.AfterMinutes = dataAO0.AfterMinutes

	m.Call = dataAO0.Call

	m.Email = dataAO0.Email

	m.IsRepeat = dataAO0.IsRepeat

	m.NotificationWindow = dataAO0.NotificationWindow

	m.NotifyWho = dataAO0.NotifyWho

	m.Sms = dataAO0.Sms

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m HTTPCheckInputAllOf0AllOf0EscalationsItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataAO0 struct {
		AfterMinutes int32 `json:"after_minutes,omitempty"`

		Call *bool `json:"call,omitempty"`

		Email *bool `json:"email,omitempty"`

		IsRepeat *bool `json:"is_repeat,omitempty"`

		NotificationWindow *HTTPCheckInputAllOf0AllOf0EscalationsItems0AO0NotificationWindow `json:"notification_window,omitempty"`

		NotifyWho []*HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0 `json:"notify_who"`

		Sms *bool `json:"sms,omitempty"`
	}

	dataAO0.AfterMinutes = m.AfterMinutes

	dataAO0.Call = m.Call

	dataAO0.Email = m.Email

	dataAO0.IsRepeat = m.IsRepeat

	dataAO0.NotificationWindow = m.NotificationWindow

	dataAO0.NotifyWho = m.NotifyWho

	dataAO0.Sms = m.Sms

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this HTTP check input all of0 all of0 escalations items0
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNotificationWindow(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNotifyWho(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0) validateNotificationWindow(formats strfmt.Registry) error {

	if swag.IsZero(m.NotificationWindow) { // not required
		return nil
	}

	if m.NotificationWindow != nil {
		if err := m.NotificationWindow.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("notification_window")
			}
			return err
		}
	}

	return nil
}

func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0) validateNotifyWho(formats strfmt.Registry) error {

	if swag.IsZero(m.NotifyWho) { // not required
		return nil
	}

	for i := 0; i < len(m.NotifyWho); i++ {
		if swag.IsZero(m.NotifyWho[i]) { // not required
			continue
		}

		if m.NotifyWho[i] != nil {
			if err := m.NotifyWho[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("notify_who" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this HTTP check input all of0 all of0 escalations items0 based on the context it is used
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateNotificationWindow(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNotifyWho(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0) contextValidateNotificationWindow(ctx context.Context, formats strfmt.Registry) error {

	if m.NotificationWindow != nil {
		if err := m.NotificationWindow.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("notification_window")
			}
			return err
		}
	}

	return nil
}

func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0) contextValidateNotifyWho(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.NotifyWho); i++ {

		if m.NotifyWho[i] != nil {
			if err := m.NotifyWho[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("notify_who" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0) UnmarshalBinary(b []byte) error {
	var res HTTPCheckInputAllOf0AllOf0EscalationsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// HTTPCheckInputAllOf0AllOf0EscalationsItems0AO0NotificationWindow HTTP check input all of0 all of0 escalations items0 a o0 notification window
//
// swagger:model HTTPCheckInputAllOf0AllOf0EscalationsItems0AO0NotificationWindow
type HTTPCheckInputAllOf0AllOf0EscalationsItems0AO0NotificationWindow struct {

	// The duration of the notification window, in minutes
	// Example: 180
	DurationInMinutes int32 `json:"duration_in_minutes,omitempty"`

	// The end time for the notification window, formatted like 1:30pm or 13:30.
	// Example: 15:00
	EndTime string `json:"end_time,omitempty"`

	// The start time for the notification window, formatted like 1:30pm or 13:30.
	// Example: 12:00
	StartTime string `json:"start_time,omitempty"`

	// The time zone for the notification window (see <a href='http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html'>list of available time zones</a>)
	// Example: Eastern Time (US \u0026 Canada)
	TimeZone string `json:"time_zone,omitempty"`
}

// Validate validates this HTTP check input all of0 all of0 escalations items0 a o0 notification window
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0AO0NotificationWindow) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this HTTP check input all of0 all of0 escalations items0 a o0 notification window based on context it is used
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0AO0NotificationWindow) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0AO0NotificationWindow) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0AO0NotificationWindow) UnmarshalBinary(b []byte) error {
	var res HTTPCheckInputAllOf0AllOf0EscalationsItems0AO0NotificationWindow
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0 Where to send escalations
//
// swagger:model HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0
type HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0 struct {

	// The recipient's email, if notifying a custom email address
	CustomEmail string `json:"custom_email,omitempty"`

	// The id of the user or group
	ID int32 `json:"id,omitempty"`

	// links
	Links *HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0Links `json:"links,omitempty"`

	// The type of recipient. Can be either `user` or `group`.
	Type string `json:"type,omitempty"`
}

// Validate validates this HTTP check input all of0 all of0 escalations items0 notify who items0
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0) validateLinks(formats strfmt.Registry) error {
	if swag.IsZero(m.Links) { // not required
		return nil
	}

	if m.Links != nil {
		if err := m.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("links")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this HTTP check input all of0 all of0 escalations items0 notify who items0 based on the context it is used
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	if m.Links != nil {
		if err := m.Links.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("links")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0) UnmarshalBinary(b []byte) error {
	var res HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0Links HTTP check input all of0 all of0 escalations items0 notify who items0 links
//
// swagger:model HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0Links
type HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0Links struct {

	// The html view for this recipient, if available
	SelfHTML string `json:"self_html,omitempty"`
}

// Validate validates this HTTP check input all of0 all of0 escalations items0 notify who items0 links
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0Links) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this HTTP check input all of0 all of0 escalations items0 notify who items0 links based on context it is used
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0Links) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0Links) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0Links) UnmarshalBinary(b []byte) error {
	var res HTTPCheckInputAllOf0AllOf0EscalationsItems0NotifyWhoItems0Links
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// HTTPCheckInputAllOf0AllOf0NotifyWhoItems0 Where to send notifications
//
// swagger:model HTTPCheckInputAllOf0AllOf0NotifyWhoItems0
type HTTPCheckInputAllOf0AllOf0NotifyWhoItems0 struct {

	// A custom email to notify. Other fields can be left blank when setting this.
	CustomEmail string `json:"custom_email,omitempty"`

	// The id of the user, group, or alert webhook
	ID int32 `json:"id,omitempty"`

	// The type of recipient. Can be either `user`, `group`, or `alert_webhook`.
	Type string `json:"type,omitempty"`

	// Notify via phone call (requires that the recipient has a valid phone number and accepts phone call alerts)
	Call *bool `json:"call,omitempty"`

	// Notify via email
	Email *bool `json:"email,omitempty"`

	// Notify via SMS (requires that the recipient has a valid phone number and accepts SMS alerts)
	Sms *bool `json:"sms,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *HTTPCheckInputAllOf0AllOf0NotifyWhoItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		CustomEmail string `json:"custom_email,omitempty"`

		ID int32 `json:"id,omitempty"`

		Type string `json:"type,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.CustomEmail = dataAO0.CustomEmail

	m.ID = dataAO0.ID

	m.Type = dataAO0.Type

	// AO1
	var dataAO1 struct {
		Call *bool `json:"call,omitempty"`

		Email *bool `json:"email,omitempty"`

		Sms *bool `json:"sms,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Call = dataAO1.Call

	m.Email = dataAO1.Email

	m.Sms = dataAO1.Sms

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m HTTPCheckInputAllOf0AllOf0NotifyWhoItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	var dataAO0 struct {
		CustomEmail string `json:"custom_email,omitempty"`

		ID int32 `json:"id,omitempty"`

		Type string `json:"type,omitempty"`
	}

	dataAO0.CustomEmail = m.CustomEmail

	dataAO0.ID = m.ID

	dataAO0.Type = m.Type

	jsonDataAO0, errAO0 := swag.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	var dataAO1 struct {
		Call *bool `json:"call,omitempty"`

		Email *bool `json:"email,omitempty"`

		Sms *bool `json:"sms,omitempty"`
	}

	dataAO1.Call = m.Call

	dataAO1.Email = m.Email

	dataAO1.Sms = m.Sms

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this HTTP check input all of0 all of0 notify who items0
func (m *HTTPCheckInputAllOf0AllOf0NotifyWhoItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this HTTP check input all of0 all of0 notify who items0 based on context it is used
func (m *HTTPCheckInputAllOf0AllOf0NotifyWhoItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPCheckInputAllOf0AllOf0NotifyWhoItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPCheckInputAllOf0AllOf0NotifyWhoItems0) UnmarshalBinary(b []byte) error {
	var res HTTPCheckInputAllOf0AllOf0NotifyWhoItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// HTTPCheckInputSuccessCriteriaItems0 A criterion for the check to pass
//
// swagger:model HTTPCheckInputSuccessCriteriaItems0
type HTTPCheckInputSuccessCriteriaItems0 struct {

	// action type
	// Required: true
	// Enum: [presence_of_text absence_of_text matches_regular_expression does_not_contain_regular_expression response_code goes_to_url]
	ActionType *string `json:"action_type"`

	// comparison string
	// Required: true
	ComparisonString *string `json:"comparison_string"`
}

// Validate validates this HTTP check input success criteria items0
func (m *HTTPCheckInputSuccessCriteriaItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActionType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateComparisonString(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var httpCheckInputSuccessCriteriaItems0TypeActionTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["presence_of_text","absence_of_text","matches_regular_expression","does_not_contain_regular_expression","response_code","goes_to_url"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		httpCheckInputSuccessCriteriaItems0TypeActionTypePropEnum = append(httpCheckInputSuccessCriteriaItems0TypeActionTypePropEnum, v)
	}
}

const (

	// HTTPCheckInputSuccessCriteriaItems0ActionTypePresenceOfText captures enum value "presence_of_text"
	HTTPCheckInputSuccessCriteriaItems0ActionTypePresenceOfText string = "presence_of_text"

	// HTTPCheckInputSuccessCriteriaItems0ActionTypeAbsenceOfText captures enum value "absence_of_text"
	HTTPCheckInputSuccessCriteriaItems0ActionTypeAbsenceOfText string = "absence_of_text"

	// HTTPCheckInputSuccessCriteriaItems0ActionTypeMatchesRegularExpression captures enum value "matches_regular_expression"
	HTTPCheckInputSuccessCriteriaItems0ActionTypeMatchesRegularExpression string = "matches_regular_expression"

	// HTTPCheckInputSuccessCriteriaItems0ActionTypeDoesNotContainRegularExpression captures enum value "does_not_contain_regular_expression"
	HTTPCheckInputSuccessCriteriaItems0ActionTypeDoesNotContainRegularExpression string = "does_not_contain_regular_expression"

	// HTTPCheckInputSuccessCriteriaItems0ActionTypeResponseCode captures enum value "response_code"
	HTTPCheckInputSuccessCriteriaItems0ActionTypeResponseCode string = "response_code"

	// HTTPCheckInputSuccessCriteriaItems0ActionTypeGoesToURL captures enum value "goes_to_url"
	HTTPCheckInputSuccessCriteriaItems0ActionTypeGoesToURL string = "goes_to_url"
)

// prop value enum
func (m *HTTPCheckInputSuccessCriteriaItems0) validateActionTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, httpCheckInputSuccessCriteriaItems0TypeActionTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *HTTPCheckInputSuccessCriteriaItems0) validateActionType(formats strfmt.Registry) error {

	if err := validate.Required("action_type", "body", m.ActionType); err != nil {
		return err
	}

	// value enum
	if err := m.validateActionTypeEnum("action_type", "body", *m.ActionType); err != nil {
		return err
	}

	return nil
}

func (m *HTTPCheckInputSuccessCriteriaItems0) validateComparisonString(formats strfmt.Registry) error {

	if err := validate.Required("comparison_string", "body", m.ComparisonString); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this HTTP check input success criteria items0 based on context it is used
func (m *HTTPCheckInputSuccessCriteriaItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HTTPCheckInputSuccessCriteriaItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HTTPCheckInputSuccessCriteriaItems0) UnmarshalBinary(b []byte) error {
	var res HTTPCheckInputSuccessCriteriaItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
