// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PerformanceKpiData performance kpi data
//
// swagger:model performance_kpi_data
type PerformanceKpiData struct {

	// The unique ID for the check.
	// Example: 1
	// Required: true
	CheckID *int32 `json:"check_id"`

	// The start time for the timeframe (UTC).
	// Example: 2021-05-25T16:54:05Z
	// Required: true
	// Format: date-time
	From *strfmt.DateTime `json:"from"`

	// A list of the metrics included in series.
	// Required: true
	Metrics []*PageMetric `json:"metrics"`

	// The predefined timeframe, if provided.
	// Example: last_hour
	// Enum: [last_hour last_4_hours last_8_hours last_12_hours last_24_hours yesterday today last_7_days last_30_days this_week last_week this_month month_to_date last_month last_3_months last_6_months last_12_months]
	Range string `json:"range,omitempty"`

	// An array of data sets, one for each page and metric combination.
	// Required: true
	Series []*PageCollectionSeries `json:"series"`

	// The end time for the timeframe (UTC).
	// Example: 2021-05-25T17:54:05Z
	// Required: true
	// Format: date-time
	To *strfmt.DateTime `json:"to"`
}

// Validate validates this performance kpi data
func (m *PerformanceKpiData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCheckID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFrom(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMetrics(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRange(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSeries(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PerformanceKpiData) validateCheckID(formats strfmt.Registry) error {

	if err := validate.Required("check_id", "body", m.CheckID); err != nil {
		return err
	}

	return nil
}

func (m *PerformanceKpiData) validateFrom(formats strfmt.Registry) error {

	if err := validate.Required("from", "body", m.From); err != nil {
		return err
	}

	if err := validate.FormatOf("from", "body", "date-time", m.From.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *PerformanceKpiData) validateMetrics(formats strfmt.Registry) error {

	if err := validate.Required("metrics", "body", m.Metrics); err != nil {
		return err
	}

	for i := 0; i < len(m.Metrics); i++ {
		if swag.IsZero(m.Metrics[i]) { // not required
			continue
		}

		if m.Metrics[i] != nil {
			if err := m.Metrics[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("metrics" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var performanceKpiDataTypeRangePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["last_hour","last_4_hours","last_8_hours","last_12_hours","last_24_hours","yesterday","today","last_7_days","last_30_days","this_week","last_week","this_month","month_to_date","last_month","last_3_months","last_6_months","last_12_months"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		performanceKpiDataTypeRangePropEnum = append(performanceKpiDataTypeRangePropEnum, v)
	}
}

const (

	// PerformanceKpiDataRangeLastHour captures enum value "last_hour"
	PerformanceKpiDataRangeLastHour string = "last_hour"

	// PerformanceKpiDataRangeLast4Hours captures enum value "last_4_hours"
	PerformanceKpiDataRangeLast4Hours string = "last_4_hours"

	// PerformanceKpiDataRangeLast8Hours captures enum value "last_8_hours"
	PerformanceKpiDataRangeLast8Hours string = "last_8_hours"

	// PerformanceKpiDataRangeLast12Hours captures enum value "last_12_hours"
	PerformanceKpiDataRangeLast12Hours string = "last_12_hours"

	// PerformanceKpiDataRangeLast24Hours captures enum value "last_24_hours"
	PerformanceKpiDataRangeLast24Hours string = "last_24_hours"

	// PerformanceKpiDataRangeYesterday captures enum value "yesterday"
	PerformanceKpiDataRangeYesterday string = "yesterday"

	// PerformanceKpiDataRangeToday captures enum value "today"
	PerformanceKpiDataRangeToday string = "today"

	// PerformanceKpiDataRangeLast7Days captures enum value "last_7_days"
	PerformanceKpiDataRangeLast7Days string = "last_7_days"

	// PerformanceKpiDataRangeLast30Days captures enum value "last_30_days"
	PerformanceKpiDataRangeLast30Days string = "last_30_days"

	// PerformanceKpiDataRangeThisWeek captures enum value "this_week"
	PerformanceKpiDataRangeThisWeek string = "this_week"

	// PerformanceKpiDataRangeLastWeek captures enum value "last_week"
	PerformanceKpiDataRangeLastWeek string = "last_week"

	// PerformanceKpiDataRangeThisMonth captures enum value "this_month"
	PerformanceKpiDataRangeThisMonth string = "this_month"

	// PerformanceKpiDataRangeMonthToDate captures enum value "month_to_date"
	PerformanceKpiDataRangeMonthToDate string = "month_to_date"

	// PerformanceKpiDataRangeLastMonth captures enum value "last_month"
	PerformanceKpiDataRangeLastMonth string = "last_month"

	// PerformanceKpiDataRangeLast3Months captures enum value "last_3_months"
	PerformanceKpiDataRangeLast3Months string = "last_3_months"

	// PerformanceKpiDataRangeLast6Months captures enum value "last_6_months"
	PerformanceKpiDataRangeLast6Months string = "last_6_months"

	// PerformanceKpiDataRangeLast12Months captures enum value "last_12_months"
	PerformanceKpiDataRangeLast12Months string = "last_12_months"
)

// prop value enum
func (m *PerformanceKpiData) validateRangeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, performanceKpiDataTypeRangePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PerformanceKpiData) validateRange(formats strfmt.Registry) error {
	if swag.IsZero(m.Range) { // not required
		return nil
	}

	// value enum
	if err := m.validateRangeEnum("range", "body", m.Range); err != nil {
		return err
	}

	return nil
}

func (m *PerformanceKpiData) validateSeries(formats strfmt.Registry) error {

	if err := validate.Required("series", "body", m.Series); err != nil {
		return err
	}

	for i := 0; i < len(m.Series); i++ {
		if swag.IsZero(m.Series[i]) { // not required
			continue
		}

		if m.Series[i] != nil {
			if err := m.Series[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("series" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *PerformanceKpiData) validateTo(formats strfmt.Registry) error {

	if err := validate.Required("to", "body", m.To); err != nil {
		return err
	}

	if err := validate.FormatOf("to", "body", "date-time", m.To.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this performance kpi data based on the context it is used
func (m *PerformanceKpiData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMetrics(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSeries(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PerformanceKpiData) contextValidateMetrics(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Metrics); i++ {

		if m.Metrics[i] != nil {
			if err := m.Metrics[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("metrics" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *PerformanceKpiData) contextValidateSeries(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Series); i++ {

		if m.Series[i] != nil {
			if err := m.Series[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("series" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PerformanceKpiData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PerformanceKpiData) UnmarshalBinary(b []byte) error {
	var res PerformanceKpiData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
