// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SeleniumSideCommand selenium side command
//
// swagger:model selenium_side_command
type SeleniumSideCommand struct {

	// command
	// Example: open
	Command string `json:"command,omitempty"`

	// The step name
	// Example: Open the first page
	Comment string `json:"comment,omitempty"`

	// target
	// Example: /path/to/follow
	Target string `json:"target,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this selenium side command
func (m *SeleniumSideCommand) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this selenium side command based on context it is used
func (m *SeleniumSideCommand) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SeleniumSideCommand) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SeleniumSideCommand) UnmarshalBinary(b []byte) error {
	var res SeleniumSideCommand
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
