// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SeleniumSideScript A Selenium SIDE script. This can be run using the Selenium IDE.
//
// swagger:model selenium_side_script
type SeleniumSideScript struct {

	// name
	// Example: Example Check
	Name string `json:"name,omitempty"`

	// suites
	Suites []*SeleniumSideSuite `json:"suites"`

	// tests
	Tests []*SeleniumSideTest `json:"tests"`

	// url
	// Example: https://example.com
	URL string `json:"url,omitempty"`

	// urls
	Urls []string `json:"urls"`

	// version
	// Example: 1.1
	Version string `json:"version,omitempty"`
}

// Validate validates this selenium side script
func (m *SeleniumSideScript) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSuites(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTests(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SeleniumSideScript) validateSuites(formats strfmt.Registry) error {
	if swag.IsZero(m.Suites) { // not required
		return nil
	}

	for i := 0; i < len(m.Suites); i++ {
		if swag.IsZero(m.Suites[i]) { // not required
			continue
		}

		if m.Suites[i] != nil {
			if err := m.Suites[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("suites" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SeleniumSideScript) validateTests(formats strfmt.Registry) error {
	if swag.IsZero(m.Tests) { // not required
		return nil
	}

	for i := 0; i < len(m.Tests); i++ {
		if swag.IsZero(m.Tests[i]) { // not required
			continue
		}

		if m.Tests[i] != nil {
			if err := m.Tests[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tests" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this selenium side script based on the context it is used
func (m *SeleniumSideScript) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSuites(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTests(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SeleniumSideScript) contextValidateSuites(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Suites); i++ {

		if m.Suites[i] != nil {
			if err := m.Suites[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("suites" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SeleniumSideScript) contextValidateTests(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Tests); i++ {

		if m.Tests[i] != nil {
			if err := m.Tests[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tests" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SeleniumSideScript) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SeleniumSideScript) UnmarshalBinary(b []byte) error {
	var res SeleniumSideScript
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
